### ISSUE TITLE
Migrate SnippetRunner to CE 3

### ISSUE THREAD

**Issue by osaman88** [kubukoz/videos#15]
Hi Jakub, do you have time to get SnippetRunner/showValues migrated to CE3?

**Comment by kubukoz** [comment]
It was starting simple so I did it in https://github.com/kubukoz/videos/tree/showvalues-ce3. Most of the difficulty is due to `debug` not appearing by default (because running an IO always shifts to CE's threads even if you straight up `unsafeRunSync()` without any explicit async boundaries). I switched to an explicit `System.out.println` (as opposed to `println` which was being used in fs2's debug by default) as a workaround.

Related: https://github.com/scalameta/mdoc/issues/517

**Comment by osaman88** [comment]
Thank you Jakub!
